In [13]:
import vugrad as vg
import numpy as np

a = vg.TensorNode(np.random.randn(2, 2))
b = vg.TensorNode(np.random.randn(2, 2))
c = a + b
print(a.value)
print(b.value)
print("=========")
print(c.value)
print(c.source)
print(c.source.inputs[0])
print(a.grad)

[[-0.75499683  1.12060124]
 [ 0.93333161 -0.44160203]]
[[ 0.29140426 -0.59145206]
 [-1.25050846 -1.04023531]]
[[-0.46359257  0.52914917]
 [-0.31717685 -1.48183734]]
TensorNode[size (2, 2), source None].
[[0. 0.]
 [0. 0.]]


In [35]:
import numpy as np
from vugrad import Op


class ReLU(Op):
    """
    Op for element-wise application of relu function
    """

    @staticmethod
    def forward(context, input):
        gtz = input > 0
        context["gtz"] = gtz
        return np.where(gtz, input, 0)

    @staticmethod
    def backward(context, goutput):
        return np.where(context["gtz"], goutput, 0)

n = ReLU()
x = np.arange(-2, 3, 1).reshape(1, 5).astype(np.float32)
gtz = np.where(x > 0, x, 0)
y = np.where(gtz, x, 0)
gx = np.where(gtz, 1, 0)
print(x)
print(y)
print(gx)
# print(np.where(gtz, x, 0))

# context = {}
# print(x, n.forward(context, x))


[[-2. -1.  0.  1.  2.]]
[[0. 0. 0. 1. 2.]]
[[0 0 0 1 1]]
